GET http://localhost:8000/member/hello
Accept: application/json

<> 2024-05-08T155207.200.json

###
GET http://localhost:8000/member/hello
Accept: application/json

###
GET http://localhost:8000/member/count
Accept: application/json

# 使用 ptrp 生成带参数的 post 请求
###
POST http://localhost:8000/member/register
Content-Type: application/x-www-form-urlencoded

mobile=12345678901
###

POST http://localhost:8000/member/member/login
Content-Type: application/x-www-form-urlencoded

mobile=123456&code=8888


> {%
    client.log(JSON.stringify(response.body));
    client.log(JSON.stringify(response.body.content.token));
    client.global.set("token", response.body.content.token);
%}
